# Simple MLflow with PostgreSQL support
FROM ghcr.io/mlflow/mlflow:v2.12.2

# Install PostgreSQL driver
RUN pip install psycopg2-binary

# Expose MLflow port
EXPOSE 5000

# Run MLflow server (command will be provided by docker-compose)
