[server]
headless = true
port = 8501
address = "0.0.0.0"
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[theme]
base = "light"
