apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: recommendation-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma:latest
        ports:
        - containerPort: 8000
        env:
        - name: CHROMA_HOST
          value: "0.0.0.0"
        - name: CHROMA_PORT
          value: "8000"
        volumeMounts:
        - name: chromadb-storage
          mountPath: /chroma/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: chromadb-storage
        persistentVolumeClaim:
          claimName: chromadb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  namespace: recommendation-system
spec:
  selector:
    app: chromadb
  ports:
  - port: 8001
    targetPort: 8000
    protocol: TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
  namespace: recommendation-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
