name: Basic Security Checks

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  basic-security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit

    - name: Run safety check (dependency vulnerabilities)
      run: |
        pip freeze | safety check --short-report

    - name: Run bandit security linter (basic security issues)
      run: |
        bandit -r app/ ai/ config/ data/ --severity-level medium

    - name: Basic dependency check
      run: |
        pip check
